const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('deskBub', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  getStarterPet: (starterId) => ipcRenderer.invoke('get-starter-pet', starterId),
  savePetSelection: (pet) => ipcRenderer.invoke('save-pet-selection', pet),
  setIgnoreMouse: (ignore, options) => ipcRenderer.invoke('set-ignore-mouse', ignore, options),
  setActions: (actions) => ipcRenderer.invoke('set-actions', actions),
  setCurrentAction: (action) => ipcRenderer.invoke('set-current-action', action),
  getActions: () => ipcRenderer.invoke('get-actions'),
  openControlPanel: () => ipcRenderer.invoke('open-control-panel'),
  controlAction: (action) => ipcRenderer.invoke('control-action', action),
  pairPet: (code) => ipcRenderer.invoke('pair-pet', code),
  useStarterPet: (starterId) => ipcRenderer.invoke('use-starter-pet', starterId),
  reportPairingResult: (result) => ipcRenderer.invoke('report-pairing-result', result),
  readClipboard: () => ipcRenderer.invoke('read-clipboard'),
  copyShareCaption: () => ipcRenderer.invoke('copy-share-caption'),
  shareMyPet: () => ipcRenderer.invoke('share-my-pet'),
  getCaptureSources: () => ipcRenderer.invoke('get-capture-sources'),
  setControlPanelVisible: (visible) => ipcRenderer.invoke('set-control-panel-visible', visible),
  saveScreenRecording: (bytes) => ipcRenderer.invoke('save-screen-recording', bytes),
  showSharedFile: () => ipcRenderer.invoke('show-shared-file'),
  openSharePlatform: (platform) => ipcRenderer.invoke('open-share-platform', platform),
  onConfigUpdated: (callback) => ipcRenderer.on('config-updated', (_, config) => callback(config)),
  onRemindersToggled: (callback) => ipcRenderer.on('reminders-toggled', (_, enabled) => callback(enabled)),
  onTrayAction: (callback) => ipcRenderer.on('tray-action', (_, action) => callback(action)),
  onPairPet: (callback) => ipcRenderer.on('pair-pet', (_, code) => callback(code)),
  onUseStarterPet: (callback) => ipcRenderer.on('use-starter-pet', (_, starterId) => callback(starterId)),
  onActionsUpdated: (callback) => ipcRenderer.on('actions-updated', (_, actions) => callback(actions)),
  onCurrentActionUpdated: (callback) => ipcRenderer.on('current-action-updated', (_, action) => callback(action)),
  onPairingResult: (callback) => ipcRenderer.on('pairing-result', (_, result) => callback(result)),
  onFocusPairing: (callback) => ipcRenderer.on('focus-pairing', callback),
  onShareResult: (callback) => ipcRenderer.on('share-result', (_, result) => callback(result)),
});
